### ISSUE TITLE
Write / Read exceptions with no clear message

### ISSUE THREAD

**Issue by azjezz** [hhvm/hsl-experimental#37] opened 2019-02-16 00:04 UTC
currently the write and read methods don't show any useful information on why was the exception thrown

example : 
-> calling read / write methods after closing the resource 
-> resource is not readable / writeable 
-> an error while calling the builtin functions ( `fwrite` / `fread` )

while reading a message stream in nuxed for example, this is handled by checking  : 
1. is the stream closed ?
-> yes. [`throw UnreadableStreamException::dueToMissingResource()`](https://github.com/nuxed/framework/blob/master/src/Nuxed/Http/Message/Exception/UnreadableStreamException.hack#L13)
-> no. continue.
2. is the stream readable ? 
-> yes. continue 
-> no. [`throw UnreadableStreamException::dueToConfiguration()`](https://github.com/nuxed/framework/blob/master/src/Nuxed/Http/Message/Exception/UnreadableStreamException.hack#L9)
3. did the `fread` function return `false` ?
-> yes. [`throw UnreadableStreamException::dueToPhpError()`](https://github.com/nuxed/framework/blob/master/src/Nuxed/Http/Message/Exception/UnreadableStreamException.hack#L17)
-> no. finish.

**Comment by fredemmott** [comment] 2019-10-21 16:12
Diff up exposing the OS-level errno code

**Comment by fredemmott** [comment] 2019-10-21 22:09
They are now distinguishable via Errno, but message should also be implemented

**Comment by fredemmott** [comment] 2019-10-23 20:21
Big question is "what should get a unique instantiable exception class?"

HSL IO will not be checking if an operation is safe to do, as this involves a race, especially when async is involved - however, it will check why an operation failed at a system level - e.g. "what is the `errno` or `herrno` variable, or the SOL_ERROR sockopt?" - this effectively splits 'fread returned false' into *many* cases.

I think this is best addressed by splitting into four questions:

# What is the purpose of distinct exception classes?

To me, this is when different errors are reasonably likely to require different handling fairly frequently - i.e. when you're likely to have multiple `catch()` blocks with different content depending on the class raised.

End-user-friendliness is not a compelling reason: `getMessage()` should address this (though doesn't in the current implementation), as should the first few frames of the stack. I'm less certain on this than my phrasing indicates :)

# Should each operation have its' own exception class?

1. Always:
  - [-] unclear if "`writeAsync` threw a `writeException`" adds anything significant over "`writeAsync`" threw a `IO\Exception` for the common case
  - [+] if you 500 with a WriteException, it's clear what went wrong without looking at any more details
  - [-] users likely to catch too-specific exceptions for rare cases to be handled, e.g. for `writeAsync()` need handle both `WriteException` and `SelectException` - likely would want same "file is closed" behavior for both.
2. No, except for implicit operations:
  - e.g. `select()` is not exposed, but is implicitly called in many places (via `stream_await()`) - e.g. `->writeAsync()`, `new Server()` etc all involve implicit selects
  - e.g. `new Server()` calls `socket()`, `bind()`, and `listen()`; the failing operation may need different handling
  - [-] users likely to catch too-specific exceptions
3. No
  - [-] users need to look at message/stack to find out what failed
     - if added to message, is not a big deal?

For (1) and (2), there's a sub-question: is there any need for a distinction between File\WriteException, IO\WriteException, and Socket\WriteException ?

# Should each cause (i.e. errno) have it's own exception class?

1. Yes, always:
  - [+] cause of failure seems the most likely reason to have distinct catch blocks
  - [-] users effectively need to be familiar with errno to use the library
  - [-] at present, ~ 150 valid causes can be returned from the OS. Usability/discoverabilty problem
2. Yes, for common cases, but with a all-in-one generic/unknown/system error class for others
  - [+] cause of failure for common cases can have distinct catch blocks
  - [-] if rare cases need to be handled, `switch($errno)` is needed in the catch blocks
  - [+] number of exception classes is whatever balance we feel is best
  - [+] if we get the set of 'common cases' defined well enough, users should not need to be familiar with errno constants
  - [+] if we don't define enough common cases, users can catch an interface exposing an enum, and we get add new 'common case' classes without introducing a BC break
3. No:
  - [-] need `switch($errno)` in all cases
  - [-] require users to be familiar with posix-like behavior

# How do the previous answers combine?

Many ways to do this, just want to outline the most obvious ones:

## Full Combination

e.g. WriteFailedDiskFull: several thousand exception classes. Bad for usability

## Wrapping

With operation as the outer exception, cause as the inner, cause is not currently catchable. Could potentially be fixed with language changes to permit:

```hack
class ReadException<reify T as CauseException> extends OperationException {
}

class FDClosedException extends CauseException {
}

try {
  // ...
} catch (ReadException<FDClosedException> $_) {
  // caught operation and cause
} catch (OperationException<FDClosedException> $_) {
  // caught cause only
} catch (ReadException<_> $_) {
  // caught operation only
} catch (ReadException<CauseException> $_) {
  // caught operation only (if variance declared correctly)
}
```

 - [=] feels unusual, but might be possible
 - [-] users are likely to catch too-specific exceptions

----

I'll be editing this comment based on responses

**Comment by fredemmott** [comment] 2019-10-23 20:27
My first choice:
 - operation: (3) never. I feel that the 'catching too-specific exception' problem is a big concern with  either of the others
  - cause (errno): (2) common cases with fallback to unknown/system/generic for rare cases: this is because I see a need to act differently on different causes, but if a codeblock fails with any particular errno (e.g. 'file does not exist', 'not writable', 'closed'), in code I'm unlikely to handle the case differently depending on operation, only on the errno. If I do, user code can catch and re-throw. For debugging, stack trace and message reveal the operation.
  - extra: add operation to the message.

This would include the removal of File\OpenException, File\ReadException, File\WriteException, File\LockAcquisitionException.

I am strongly against "full combination" regardless of how many are needed.

I'll follow-up with the hack team on if reified catch should be permitted, regardless of if it's used here.

**Comment by jjergus** [comment] 2019-10-25 20:18
I agree with using "what would a reasonable person want to catch" as the primary design goal.

Based on your latest suggestion -- does that mean there would be no exceptions in any namespace except `IO`? e.g. only `IO\WriteException`, not `File\WriteException` or `Socket\WriteException` etc.?

Are there any reasonable cases where someone would want to catch a "file write" exception but a generic "write" exception would be too broad? like some common operation that does multiple different types of writes that can go wrong?

> add operation to the message

maybe worth adding more structured data to the exception class? e.g. an enum for operation -- I'm not sure how feasible that is, or if it's any better than just having multiple exception classes

**Comment by azjezz** [comment] 2019-10-25 20:51
> Are there any reasonable cases where someone would want to catch a "file write" exception but a generic "write" exception would be too broad? like some common operation that does multiple different types of writes that can go wrong?

i believe so : 

```hack
try {
  $connection = await $this->server->next();
  ($id, $request) = await $this->capture($connection);
  concurrent {
    await $this->logger->debug(Str\format(
      '[%s] %s %s',
      $id,
      $request->getMethod(),
      $request->getRequestTarget()
    ), dict['request' => $request]);

    $response = await $this->handler->handle($request);
  }
  concurrent {
    await $this->logger->debug(Str\format(
      '[%s] %d %s',
      $id,
      $response->getStatusCode(),
      $response->getStatusPhrase()
    ), dict['request' => $request, 'response' => $response]);
    await $this->respond($connection, $response);
  }
} catch(Network\ReadException $exception) {
  // exception thrown while reading the request
} catch(Network\WriteException $exception) {
  // exception thrown while responding
} catch(File\WriteException $exception) {
  // exception thrown while logging.
}
```

**Comment by jjergus** [comment] 2019-10-25 21:19
I think in that example the try/catch block is too broad -- there should be multiple smaller try/catch blocks about specific operations. I know the `concurrent` blocks makes that harder but I would still say it's the right to do.

**Comment by azjezz** [comment] 2019-10-25 21:36
You are right, and in my case i won't face that issue since i usually wrap exceptions always with domain specific exception ( e.g : $logger would only throw exceptions implementing `Nuxed\Log\Exception\IException` )

however, what i would prefer is to have an exception for each operation *at least* : 
- `IO\HandleException extends IO\Exception`
thrown when `closeAsync()`, or `isEndOfFile()` fails.

- `IO\WriteException extends IO\Exception`
thrown when `writeAsync()`, or `writeRawBlocking()` fails.

- `IO\FlushException extends IO\WriteException`
thrown when `flushAsync()` fails

- `IO\ReadException extends IO\Exception`
thrown when `readAsync()`,  `readLineAsync()`, or `readRawBlocking()` fails

- `IO\SeekException extends IO\Exception`
thrown when `seekAsync()`, or `tell()` fails

- `IO\InvalidArgumentException extends IO\Exception`
thrown when an invalid argument is provided to any of the methods.

- `IO\RuntimeException extends IO\Exception`
thrown when a unexpected behaviour happens at runtime. ( e.g `selectAsync()` fails )

- `IO\UnexceptedValueException extends IO\Exception`
thrown when a call to another method returns an unexpected value internally.

to answer @fredemmott questions : 

> What is the purpose of distinct exception classes?
see above.

> Should each operation have its' own exception class?
see above.

> Should each cause (i.e. errno) have it's own exception class?
maybe for common errors, but i would say no.

**Comment by fredemmott** [comment] 2019-10-25 21:55
> Based on your latest suggestion -- does that mean there would be no exceptions in any namespace except IO? e.g. only IO\WriteException, not File\WriteException or Socket\WriteException etc.?

A mix:
- I expect unique exceptions like Network\HostResolutionException
- no duplicate exceptions, so no, no File\WriteException or Socket\WriteException

> maybe worth adding more structured data to the exception class? e.g. an enum for operation -- I'm not sure how feasible that is, or if it's any better than just having multiple exception classes

I think enums generally would be better as it's structured data, but I don't think they can work with userspace implementations which could add new operations, and enums do not support subtyping

@azjezz : I'm going to paraphrase your answers:

> What is the purpose of distinct exception classes?

Based on your examples, to indicate what failed, not how it failed.

> Should each operation have its' own exception class?

No, except for implicit operations

It looks like this would be `RuntimeException` or UnexpectedValueException`, however I'm not seeing how they differ

> Should each cause (i.e. errno) have it's own exception class?

No.

----

I'd appreciate corrections to that summary, and a rationale or some comments on why it's better rather than just a statement of preference.

**Comment by fredemmott** [comment] 2019-10-25 22:13
I think our perspective do differ a bit at a low-level that are probably worth clarifying before trying to get consensus - apologies in advance if I'm framing your view incorrectly:

# Is "`\fopen()` returned `false`" a failure cause?

You: yes
Me: no: the return value of `fopen()` is basically a straight port of the C function, which is unable to either indicate cause in the return value or throw exceptions (because they don't exist in C) - the cause is in `errno`

# Are people more likely to want to `catch(OperationThatFailed)` or `catch(CauseOfFailure)`?

You: OperationThatFailed
Me: CauseOfFailure

Is this accurate?

**Comment by azjezz** [comment] 2019-10-25 22:14
yes, but all exceptions would probably have `getErrno` which returns `CauseOfFailure` :)

**Comment by fredemmott** [comment] 2019-10-28 17:41
Comparisons (will delete comments adding to this and merge in data):

|Language/Library|Is 'call failed' a cause?|catch(Operation) or catch(CauseOfFailure)|
|---|---|---|
|OCaml|Sort-of: `Unix.Unix_error(errno, operation, param)`| either: `with Unix.error (_, "fopen", _)` or `with Unix.error (Unix.ENOENT, _, _)`
|C|Arguable; per man pages, no - cause is in errno|n/a: check result or check `errno`|
|PHP|Yes|n/a: check result or check `posix_get_last_error()`|
|PHP SplFileObject::__construct|No: RuntimeExxception if cant' be opened, LogicException if dir|CauseOfFailure|
|PHP SplFileObject::fwrite()|Yes|n/a: check result or `posix_get_last_error()`|
|C++ *fstream|No|catch(Class) - e.g. std::ifstream::failure|
| C++ Qt|Yes|n/a - bool return value, errno not exposed; error *string* is exposed|
|Java|No|catch(CauseOfFailure) via IOException subclasses)|
|Ruby|no|catch(CauseOfFailure) via SystemCallError subclasses - e.g. Errno::ENOENT (which is an exception class|

**Comment by fredemmott** [comment] 2019-10-28 17:41
OCaml's approach is pretty similar to the reified generics catch I mentioned above, though that's not currently supported

**Comment by fredemmott** [comment] 2019-10-28 20:08
I'm currently preferring:
- provide the operation in the message somehow
- exception class indicates cause

In addition to what I covered in my previous responses:
- most consistent with the more modern designs, Java, Ruby, Python. Also consistent with PHP SplFileObject::__construct, but SplFileInfo is internally inconsistent with it's approach here.
- per-operation can be covered with finer-grained try-catch blocks and probably should - ideally converting to higher-level exceptions like the 'LoggingException' mentioned above. The example of using File\WriteException vs Network\WriteException is extremely brittle: in the concrete case, request_output() is a base IO\WriteHandle only, but more generally, it would break if concrete handles were replaced with MemoryHandles for testing.
  - it is likely needed for in-depth debugging; this case is covered by the stack trace
- I don't think the implicit operations need to be exposed: I can't see a reason for different handling whether an fwrite() fails or if an implicit select between fwrite() fails. Either way, the file can't be written, and the action to fix will depend on the errno rather than the operation

As for more-specific exceptions vs a cause enum:
- for the common cases, I don't want users to have to be familiar with POSIX errno names. They're really unfriendly (`ENOENT` vs `FileNotFound`)
  - it's fairly likely that many developers will not catch these, and they will propagate to users. `myscript itypoed.txt` by a less-technical user is less likely to result in a support request/github issue if it says 'file not found' than 'ENOENT'
- I don't want `catch(IO\Exception $e) { switch($e->getErrno()) {` to be the most common pattern. It is likely needed in some cases though
- for more specialized code, it's likely that people will need access to the raw errno, so the raw values should be exposed for consistency
- enums do not allow duplicate values - so we can't have `FileNotFound` and `ENOENT` in the same enum.
- enums do not allow subtyping - we can't have a typesafe `CommonErrors` and `Errno`

This leads me to strongly preferring Python's approach here:
- base class provides errno
- subclasses for commonly needed values

**Comment by fredemmott** [comment] 2019-10-28 20:20
python2 throws `IOError` with e.errno and e.strerror
python3 has the approach I described above (OSError+subclasses)

**Comment by jjergus** [comment] 2019-10-28 20:35
@azjezz:

> You: OperationThatFailed
> yes, but all exceptions would probably have getErrno which returns CauseOfFailure :)

Do you think this is preferable over "exception class is CauseOfFailure, OperationThatFailed included inside the exception object" or are you OK with both versions, as long as both the OperationThatFailed and the CauseOfFailure are included somehow?

> per-operation can be covered with finer-grained try-catch blocks and probably should

This is my view as well. I recognize that wrapping every line of code in a separate try-catch block is not feasible (especially if `concurrent` blocks are involved), so I can see the argument against it, but I don't think using OperationThatFailedException as the exception class is a solution:

For example, if there were 2 instances of the same operation in your example (e.g. writing to 2 sockets, or writing to 2 files, instead of writing to a socket and a file), the approach would not work and wrapping each operation in a separate try-catch block would be the only way to distinguish them.

With CauseOfFailureException that stores information about the operation inside, we could possibly store the filename/handle/etc. in the exception object so that even if you prefer non-granular try-catch blocks, it would still be possible to distinguish what exactly failed.

**Comment by fredemmott** [comment] 2019-10-28 20:43
Python 2->3:
- PEP (RFC): https://www.python.org/dev/peps/pep-3151/
- 'ideas' discussion: https://grokbase.com/t/python/python-ideas/107nv8vf0h/pep-3151-reworking-the-os-and-io-exception-hierarchy
- 'dev' discussion: https://mail.python.org/pipermail/python-dev/2011-August/112992.html

**Comment by fredemmott** [comment] 2019-10-28 21:13
Reading through the Python3 discussions, I think that if we expose errno classes, we shouldn't have `IO\Exception`: taking `EPERM` as an example:

- this can be an error with other calls, and not actually related to IO permissions, e.g. `pthread_cond_time_wait`
- we shouldn't throw an `IO\EPERMException` (... with a different name) for that error as it's not IO
- ... but if we end up defining `OS\EPERMException`, `catch (OS\EPERMException $_)` should catch `IO\EPERMException`
- ... and if we do this:
   -  we're going to end up with a similar exploding-number-of-types problem like we have with the non-exception Handle classes
   - we're likely to need exception interfaces with private implementation classes for consistency:
      - we allow a single base *class*
      - if `IO\EPERMException` is a class, does it extend `IO\Exception` or `OS\Exception`, with the other being an interface? The only consistent answer is both are interfaces
- this feels like the same 'per-operation can be covered with finer-grained try-catch blocks' discussion above, just out another level

**Comment by fredemmott** [comment] 2019-10-28 21:39
a slight rework would be needed to fit with the Hack type system: we want a base class defining `getErrno(): Errno`

This means either:
- the socket exceptions (gai and herr) can not extend `OS\Exception`
- a hierarchy like following (with some naming bikeshedding needed):

```
- OS\Exception
  - Network\HErrorException
  - Network\GAIException
  - OS\ErrnoException
    - OS\NotFoundException
    - ....
```

**Comment by fredemmott** [comment] 2019-10-28 22:24
> With CauseOfFailureException that stores information about the operation inside, we could possibly store the filename/handle/etc. in the exception object so that even if you prefer non-granular try-catch blocks, it would still be possible to distinguish what exactly failed.

Can do if it helps debugging - but assuming we kill off `IO\Exception`, there's not an obvious best way to do this; some ideas are:

- OS\Exception having `getContext(): mixed` or similar: dislike as it's mixed
  - `OS\Exception<TContext> { public function getContext(): TContext }`: I like this, but I don't want to do this until `catch` at least supports `catch (OS\Exception<_>` rather than just `catch(OS\Exception`.
- having an `IO\OperationFailed` exception as the inner/previous exception: I dislike this as we'd have an exception type that would never be explicitly thrown

**Comment by jjergus** [comment] 2019-10-28 22:38
> This means either: the socket exceptions (gai and herr) can not extend OS\Exception...

Is it actually important that our error numbers match the POSIX(?) errno standard? Otherwise we could just have one big enum with all the possible errors (the enum values would become meaningless).

**Comment by fredemmott** [comment] 2019-10-28 23:16
No; we could do this; I'd rather not having them completely meaningless and have them correlated though, as it makes `var_dump($x->getErrno())` (which gives you a number) meaningful and allows `$err = \posix_get_last_error() as Errno`

We could do correlated with block allocation; constraints are:
- 0 is reserved for success
- technically, `Math\INT32_MIN` -> `Math\INT32_MAX` are unsafe to use: posix requires `int` be /at least/ a signed 16-bit integer, but OSes are free to allocate additional implementation-defined
- in practice, negative numbers won't be allocated for risk of breaking BC; it's fairly common for C libraries to return meaningful positive ints for success and `-errorcode` for failure; this means we can use them.
- This means we have `Math\INT64_MIN` -> -1 and `Math\INT32_MAX + 1` -> `Math\INT64_MAX` for us to safely use without risk

PHP's `socket_last_error()` uses `-(10000+herror)`; I dislike it there mostly as it's an undocumented opaque value, but that's easily fixable in the HSL just by documenting it clearly.

I'm currently doing:
- positive numbers: errno
- negative numbers: errno that is not supported on the current platform, matching some other platform version

Perhaps:
- 1->INT32_MAX: errno
- 10,000,000,001: herror = 1
- 20,000,000,001: gae error = 1
- negative numbers: any of the above that is not supported on the current platform

10,000,000,000 chosen for being the first power of (10 > 2^32); choosing power of 10 for human readability and computers not caring.

**Comment by fredemmott** [comment] 2019-10-28 23:21
If we do that, perhaps:

- have OS\Errno, OS\HError, OS\GAEError
- have base OS\ErrorCode codegenned from the above
- expose `getErrorCode(): OS\ErrorCode` instead of `Errno`; provide `getErrno()` in subclasses?

The potential value would be allowing completeness checks for herrno and gai errors (in the gai_strerror man page) - unsure if that's actually valuable though.

**Comment by jjergus** [comment] 2019-10-29 00:21
For arbitrary values: If human readability of var_dump output is the main goal, perhaps just use strings like "errno_42", "herror_25", etc.? I like that more than ints with arbitrary offsets.

> expose getErrorCode(): OS\ErrorCode instead of Errno; provide getErrno() in subclasses?

For any exception class, I'd expose the more specific one (errno, herrno, gaierror) iff all its subclasses agree on which one; otherwise (if there are any 2 subclasses that each have a different kind of error code) expose OS\ErrorCode.

> The potential value would be allowing completeness checks for herrno and gai errors (in the gai_strerror man page) - unsure if that's actually valuable though.

Well it doesn't cost us much so sure why not.

**Comment by fredemmott** [comment] 2019-10-29 00:25
Works for me; I was thinking “yay int comparisons” but if the perf difference isn’t negligible with it only being in error cases, something’s very wrong :p

**Comment by fredemmott** [comment] 2019-10-29 00:26
Probably having them equal to their names, and do int -> name in C to avoid this hard coded lookup list, falling back to errno_123 if we see something new

**Comment by fredemmott** [comment] 2019-10-30 17:55
> per-operation can be covered with finer-grained try-catch blocks and probably should

There is a problem with this combined with disposables: function-level `using` is not permitted in try-catch, and `using` with blocks does not provide an appropriate place to put the block - e.g.:

```hack
try {
  await using ($f = File\open_write_only($path)) {
    using ($f->lock(File\LockType::EXCLUSIVE_NON_BLOCKING)) {
      await $f->writeAsync('foo');
    }
  }
} catch ( /* ... */) {}
```

A few options come to mind:
- assume that certain kinds of errors are only raised by certain calls - e.g. EAGAIN can only be raised by `lock()` - in other cases, it will be re-attempted after a `select()`
- make disposable functions return a operation-based exception that wraps the cause exception (inconsistent)
- put an inner try/catch inside each using block to distinguish between the block failing and the using parameter expression failing. Deep nesting, pretty unreadable
- `await using $file = some_wrapper(() ==> File\open_write_only($path), $e ==> handle_error($e)`

**Comment by jjergus** [comment] 2019-10-30 18:34
> assume that certain kinds of errors are only raised by certain calls

If this is a safe assumption then it probably makes sense to create a parent class for those exceptions named after the operation (LockException...) -- basically getting the best of both worlds, anyone can catch either the cause or the operation.

**Comment by fredemmott** [comment] 2019-10-30 18:51
Sadly they're not completely separate; it's more like "assume that out of the calls you're making, the errnos you care about can not be raised by more than one"

**Comment by fredemmott** [comment] 2019-10-31 16:49
I don't really like it, but - assuming we don't get rid of first-class disposables and replace it with `await using CloseOnExit($handle)` or similar, I think the best is to make the 'acquisition' disposable functions throw their on exceptions

e.g.

```hack
namespace HH\Lib\File;

<<__ReturnDisposable>>
function open_write_only($path): DisposableFileWriteHandle {
  try {
    $raw = open_write_only_nd($path);
    return new DisposableWrapper($raw);
  } catch (IO\Exception $e) {
    throw new OpenFailedException($e);
  }
}
```

**Comment by fredemmott** [comment] 2019-10-31 20:29
We believe:
- in general, EAGAIN and EINTR should be silently retried and not returned to the user
- any other errno from fopen/write is an actual error
- there is no need to distinguish between fopen/fwrite for those errors
- flock(fd, foo | LOCK_NB) giving EWOULDBLOCK (a.k.a EAGAIN) *is not an error*: it is expected, documented behavior, explicitly requested by the caller
  - this is likely the case for any other function where the manpage calls it `EWOULDBLOCK` instead of `EAGAIN`; it is at least cause for investigation

This can likely be resolved by:

- removing the blocking/non-blocking variants from the `LockType` enum: it would just be `SHARED` and `EXCLUSIVE`
- `$file->lock(LockType)` will always block. Any errno makes it throw an OS\Exception
   - hopefully we can add a `$file->lockAsync()`, but I'm not seeing the primitives necessary to do that efficiently in the manpage
- add `$file->tryLockx(LockType)`; EWOULDBLOCK makes it throw a LockAcquisitionException, anything else throws the OS\Exception
- DO NOT ADD `$file->tryLock()`: this would need to return ?Disposable, which isn't supported.
- maybe add `$file->tryLockND()`; probably unneeded though

**Closed** 2019-11-04 23:37 UTC
